export const SAVE_USERINFO = 'SAVE_USERINFO';
export const REGISTER_USER = 'REGISTER_USER';
export const LOGOUT_USER ='LOGOUT_USER';
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
export const TECH_FOUNDED='TECH_FOUNDED';
export const TECH_UNFOUNDED='TECH_UNFOUNDED';

export const SHOW_ERROR_ALERT='SHOW_ERROR_ALERT';
export const SHOW_SUCCESS_ALERT='SHOW_SUCCESS_ALERT';
export const HIDE_ALERT_BOX='HIDE_ALERT_BOX';
export const SHOW_TITLE='SHOW_TITLE';
export const HIDE_TITLE='HIDE_TITLE';
export const REQUEST_ACCEPTED='REQUEST_ACCEPTED';
export const REQUEST_DECLIENED='REQUEST_DECLIENED';
export const SHOW_TIME_CUSTOMER='SHOW_TIME_CUSTOMER';
export const HIDE_TIME_CUSTOMER='HIDE_TIME_CUSTOMER';

export const HIDE_TASK_MODAL='HIDE_TASK_MODAL';

export const SHOW_TRANSACTION_SLIP= 'SHOW_TRANSACTION_SLIP';

export const LOGOUT_LOADER= 'LOGOUT_LOADER';